function [ s ] = tb_HP_Filter_Struct(low_CutoffFrequency,transitionBandFreqWidth,stopbandRippleAttenuation,passbandAttenuationRipple, filterChoice, tolerance, Imp_Length )
%% builds a struct for the data used in HP filter

    
    s = struct('low_CutoffFrequency', low_CutoffFrequency,...
        'transitionBandFreqWidth',transitionBandFreqWidth,...
        'stopbandRippleAttenuation', stopbandRippleAttenuation,...
        'passbandAttenuationRipple', passbandAttenuationRipple,...
        'filterChoice',filterChoice,...
        'tolerance', tolerance,...
        'filterMaxLength',Imp_Length);


end